version: "2.27.0"
services:


  postgres:
    image: postgres:16.2-bullseye
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_USER: ${STORAGE_USER?err}
      POSTGRES_DB: ${STORAGE_DATABASE?err}
      POSTGRES_PASSWORD: ${STORAGE_PASSWORD?err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5
