version: "2.27.0"
services:
  renting:
    build: .
    ports:
      - "${HTTP_PORT?err}:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DSN: "host=postgres user=${STORAGE_USER?err} password=${STORAGE_PASSWORD?err} dbname=${STORAGE_DATABASE?err} port=${STORAGE_PORT?err} sslmode=disable"
      CIPHER_KEY: ${CIPHER_KEY?err}
      HTTP_PORT: ${HTTP_PORT?err}

  postgres:
    image: postgres:16.2-bullseye
    ports:
      - "${STORAGE_PORT?err}:5432"
    user: postgres
    environment:
      POSTGRES_USER: ${STORAGE_USER?err}
      POSTGRES_DB: ${STORAGE_DATABASE?err}
      POSTGRES_PASSWORD: ${STORAGE_PASSWORD?err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5
