// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package renting

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type House struct {
	ID        int64
	Address   string
	Year      int32
	Developer pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdateAt  pgtype.Timestamp
}
